services:
  pg:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=brevly
    volumes:
      - pg_data:/bitnami/postgresql

  server:
    build: ./server
    ports:
      - "3333:3333"
    environment:
      - PORT=3333
      - NODE_ENV=production
      - DATABASE_URL=postgres://docker:docker@pg:5432/brevly
      - BASE_SHORT_URL=http://localhost:3333
      - CLOUDFLARE_ACCOUNT_ID=${CLOUDFLARE_ACCOUNT_ID}
      - CLOUDFLARE_ACCESS_KEY_ID=${CLOUDFLARE_ACCESS_KEY_ID}
      - CLOUDFLARE_SECRET_ACCESS_KEY=${CLOUDFLARE_SECRET_ACCESS_KEY}
      - CLOUDFLARE_BUCKET=${CLOUDFLARE_BUCKET}
      - CLOUDFLARE_PUBLIC_URL=${CLOUDFLARE_PUBLIC_URL}
    depends_on:
      - pg

  web:
    build: 
      context: ./web
      args:
        - VITE_BACKEND_URL=http://localhost:3333
        - VITE_FRONTEND_URL=http://localhost:5173
    ports:
      - "5173:5173"
    depends_on:
      - server

volumes:
  pg_data: